# Generated by Django 5.1 on 2025-06-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daroo',
        ),
    ]
