# Generated by Django 5.1 on 2025-07-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_sent',
        ),
    ]
