# Generated by Django 5.1 on 2025-07-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_order_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_sent',
        ),
    ]
