# Generated by Django 5.1 on 2025-07-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
