# Generated by Django 5.1 on 2025-06-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daroos_app', '0002_daroo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='daroo',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
