# Generated by Django 5.1 on 2025-07-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daroos_app', '0003_daroo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daroo',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='daroo',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='daroo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='daroo_images/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='daroo',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='daroo',
            name='title',
            field=models.CharField(max_length=60, verbose_name='عنوان'),
        ),
    ]
