# Generated by Django 5.1 on 2025-07-15 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daroos_app', '0004_alter_daroo_category_alter_daroo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
            ],
        ),
        migrations.AlterField(
            model_name='daroo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Daroos_app.category', verbose_name='دسته\u200cبندی'),
        ),
    ]
