# Generated by Django 5.1 on 2025-07-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daroos_app', '0005_category_alter_daroo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daroo',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='دسته بندی'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
